// Traffic vehicle pixel art (rear views) as ASCII data. Characters map to
// theme palette roles; B/b take the vehicle's colour variant (carA/carB/carC).

/** Vehicle sprite character → theme palette role ('B'/'b' are resolved per variant). */
export const VEHICLE_CHAR_ROLES = {
  o: 'outline', K: 'tire', g: 'glass', c: 'chrome', L: 'taillight',
  X: 'cargo', x: 'cargoShade',
};

/** Body colour variants: [main role, shade role] for 'B' and 'b'. */
export const VEHICLE_VARIANTS = [
  ['carA', 'carAShade'],
  ['carB', 'carBShade'],
  ['carC', 'carCShade'],
];

export const VEHICLE_SPRITES = {
  sedan: {
    bodyRows: [1, 22],
    rows: [
      '.............oooooooooooooooooooooooooooo.............',
      '............oBBBBBBBBBBBBBBBBBBBBBBBBBBBBo............',
      '...........ooBBBBBBBBBBBBBBBBBBBBBBBBBBBBoo...........',
      '..........oBBBgccccccccccccccccccccccccgBBBo..........',
      '..........oBBBggggggggggggggggggggggggggBBBo..........',
      '..........oBBBggggggggggggggggggggggggggBBBo..........',
      '..........oBBBggggggggggggggggggggggggggBBBo..........',
      '..........oBBBggggggggggggggggggggggggggBBBo..........',
      '..........oBBBggggggggggggggggggggggggggBBBo..........',
      '.....ooooooBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBoooooo.....',
      '....oBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBo....',
      '....oBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBo....',
      '...ooBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBoo...',
      '..oBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBo..',
      '..oBBLLLLLLLLBBBBBBBBBBBBBBBBBBBBBBBBBBBBLLLLLLLLBBo..',
      '..oBBLLLLLLLLBBBBBBBBBccccccccccBBBBBBBBBLLLLLLLLBBo..',
      '..oBBLLLLLLLLBBBBBBBBBccccccccccBBBBBBBBBLLLLLLLLBBo..',
      '..oBBBBBBBBBBBBBBBBBBBccccccccccBBBBBBBBBBBBBBBBBBBo..',
      '..oBBBBBBBBBBBBBBBBBBBccccccccccBBBBBBBBBBBBBBBBBBBo..',
      '..obbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbo..',
      '..obbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbo..',
      '.occcccccccccccccccccccccccccccccccccccccccccccccccco.',
      '.occcccccccccccccccccccccccccccccccccccccccccccccccco.',
      '..ooKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKoo..',
      '...oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo...',
      '...oKKKKKKKKooooooooooooooooooooooooooooooKKKKKKKKo...',
      '...oKKKKKKKKo............................oKKKKKKKKo...',
      '...oKKKKKKKKo............................oKKKKKKKKo...',
    ],
  },
  coupe: {
    bodyRows: [1, 17],
    rows: [
      '................oooooooooooooooooooooooooo................',
      '..............ooBBBBBBBBBBBBBBBBBBBBBBBBBBoo..............',
      '.............oBBBggggggggggggggggggggggggBBBo.............',
      '.............oBBBggggggggggggggggggggggggBBBo.............',
      '.............oBBBggggggggggggggggggggggggBBBo.............',
      '..ooooooooooooBBBggggggggggggggggggggggggBBBoooooooooooo..',
      '.obbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbo.',
      '.obbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbo.',
      '..ooBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBoo..',
      '...oBBKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKBBo...',
      '...oBBKLLLLLLLLKKKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLLKBBo...',
      '...oBBKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKBBo...',
      '...oBBBBBBBBBBBBBBBBBBBBccccccccccBBBBBBBBBBBBBBBBBBBBo...',
      '...oBBBBBBBBBBBBBBBBBBBBccccccccccBBBBBBBBBBBBBBBBBBBBo...',
      '...obbbbbbbbbbbbbbbbbbbbccccccccccbbbbbbbbbbbbbbbbbbbbo...',
      '...obbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbo...',
      '..occcccccccccccccccccccccccccccccccccccccccccccccccccco..',
      '..occcccccccccccccccccccccccccccccccccccccccccccccccccco..',
      '...oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo...',
      '...oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo...',
      '...oKKKKKKKKKooooooooooooooooooooooooooooooooKKKKKKKKKo...',
      '...oKKKKKKKKKo..............................oKKKKKKKKKo...',
      '...oKKKKKKKKKo..............................oKKKKKKKKKo...',
      '....ooooooooo................................ooooooooo....',
    ],
  },
  van: {
    bodyRows: [1, 30],
    rows: [
      '....oooooooooooooooooooooooooooooooooooooooooooooo....',
      '...oBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBo...',
      '...oBBBBBBBBBBBBBBBBBBBBBBbbBBBBBBBBBBBBBBBBBBBBBBo...',
      '...oBBBBBBBBBBBBBBBBBBBBBBbbBBBBBBBBBBBBBBBBBBBBBBo...',
      '...oBBBggggggggggggggggggBbbBggggggggggggggggggBBBo...',
      '...oBBBggggggggggggggggggBbbBggggggggggggggggggBBBo...',
      '...oBBBggggggggggggggggggBbbBggggggggggggggggggBBBo...',
      '...oBBBggggggggggggggggggBbbBggggggggggggggggggBBBo...',
      '...oBBBggggggggggggggggggBbbBggggggggggggggggggBBBo...',
      '...oBBBggggggggggggggggggBbbBggggggggggggggggggBBBo...',
      '...oBBBggggggggggggggggggBbbBggggggggggggggggggBBBo...',
      '...oBBBggggggggggggggggggBbbBggggggggggggggggggBBBo...',
      '...oBBBggggggggggggggggggBbbBggggggggggggggggggBBBo...',
      '...oBBBggggggggggggggggggBbbBggggggggggggggggggBBBo...',
      '...oBBBBBBBBBBBBBBBBBBBBBBbbBBBBBBBBBBBBBBBBBBBBBBo...',
      '...oBBBBBBBBBBBBBBBBBBBBBBbbBBBBBBBBBBBBBBBBBBBBBBo...',
      '...oBBBBBBBBBBBBBBBBBBBBBBbbBBBBBBBBBBBBBBBBBBBBBBo...',
      '...oBLLLLBBBBBBBBBBBBBBBBBbbBBBBBBBBBBBBBBBBBLLLLBo...',
      '...oBLLLLBBBBBBBBBBBBBBBBBbbBBBBBBBBBBBBBBBBBLLLLBo...',
      '...oBLLLLBBBBBBBBBBBBBBBBBbbBBBBBBBBBBBBBBBBBLLLLBo...',
      '...oBLLLLBBBBBBBBBBBBccccccccccccBBBBBBBBBBBBLLLLBo...',
      '...oBLLLLBBBBBBBBBBBBccccccccccccBBBBBBBBBBBBLLLLBo...',
      '...oBLLLLBBBBBBBBBBBBccccccccccccBBBBBBBBBBBBLLLLBo...',
      '...oBBBBBBBBBBBBBBBBBccccccccccccBBBBBBBBBBBBBBBBBo...',
      '...obbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbo...',
      '...obbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbo...',
      '...obbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbo...',
      '...obbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbo...',
      '...obbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbo...',
      '..occcccccccccccccccccccccccccccccccccccccccccccccco..',
      '..occcccccccccccccccccccccccccccccccccccccccccccccco..',
      '...ooKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKoo...',
      '....oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo....',
      '....oKKKKKKKKooooooooooooooooooooooooooooKKKKKKKKo....',
      '....oKKKKKKKKo..........................oKKKKKKKKo....',
      '....oKKKKKKKKo..........................oKKKKKKKKo....',
      '....oKKKKKKKKo..........................oKKKKKKKKo....',
      '.....oooooooo............................oooooooo.....',
    ],
  },
  truck: {
    bodyRows: [1, 43],
    rows: [
      '..oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..',
      '.oXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oXXXXXXxXXXXXXXxXXXXXXXxXXXXXxxxXXXXXXXxXXXXXXXxXXXXXXXXXXXo.',
      '.oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo.',
      '.oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo.',
      '.oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo.',
      '.oBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBo.',
      '.oBBLLLLLLBBBBBBBBBBBBBBccccccccccccccBBBBBBBBBBBBBBLLLLLLBBo.',
      '.oBBBBBBBBBBBBBBBBBBBBBBccccccccccccccBBBBBBBBBBBBBBBBBBBBBBo.',
      'occcccccccccccccccccccccccccccccccccccccccccccccccccccccccccco',
      'occcccccccccccccccccccccccccccccccccccccccccccccccccccccccccco',
      '.oooKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKooo.',
      '...oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo...',
      '...oKKKKKKKKKKKKKKKKKKKKooooooooooooooKKKKKKKKKKKKKKKKKKKKo...',
      '...oKKKKKKKKKKKKKKKKKKKKo............oKKKKKKKKKKKKKKKKKKKKo...',
      '...oKKKKKKKKKKKKKKKKKKKKo............oKKKKKKKKKKKKKKKKKKKKo...',
      '...oKKKKKKKKKKKKKKKKKKKKo............oKKKKKKKKKKKKKKKKKKKKo...',
      '...oKKKKKKKKKKKKKKKKKKKKo............oKKKKKKKKKKKKKKKKKKKKo...',
      '....oooooooooooooooooooo..............oooooooooooooooooooo....',
    ],
  },
};
