// Roadside sprite pixel art as ASCII data. Characters map to theme palette
// roles (SPRITE_CHAR_ROLES), so every sprite is recoloured by the active theme.
// worldWidth is the sprite width in world units (road half width = 2000);
// collide is the solid share of that width (0 = passable, e.g. bushes).

/** Sprite character → theme palette role. '.' is transparent. */
export const SPRITE_CHAR_ROLES = {
  o: 'outline',
  t: 'trunk', T: 'trunkDark',
  l: 'leaf', d: 'leafDark', L: 'leafLight',
  r: 'rock', q: 'rockDark', R: 'rockLight',
  c: 'cactus', k: 'cactusDark', C: 'cactusLight',
  s: 'signFace', f: 'signFrame', m: 'signMark',
  p: 'post', P: 'postDark', x: 'reflector',
  a: 'billboardA', b: 'billboardB', w: 'billboardText',
};

export const WORLD_SPRITES = {
  palm: {
    worldWidth: 1500,
    collide: 0.2,
    rows: [
      '......................oo.oo.............',
      '..................ooooLLoLLoooo.........',
      '................ooLLLLLLLLLLLLLoo.......',
      '.............oooLLLLLLLLLLLLLLLLLooo....',
      '............oLLLllLLLLLLLLLLLLLLLLLLo...',
      '...........oLLllLLLlllllllllllLLLLLLLo..',
      '..........oollLLLlldddddddddddllLLLLLoo.',
      '.........oLlldlllddddddTddddddddllllLLLo',
      '........oLLlllldddooooTTTTooooodddllllLL',
      '.......oLllddooooo..ottttTo....oooooddll',
      '......oLlddoo.......ottttTo.........oodd',
      '.....olldoo.........otttTo............oo',
      '....olldo...........oTTTTo..............',
      '.....ooo............oTTTTo..............',
      '....................oTTTTo..............',
      '...................ottttTo..............',
      '...................ottttTo..............',
      '...................ottttTo..............',
      '...................oTTTTTo..............',
      '...................oTTTTo...............',
      '...................oTTTTo...............',
      '..................ottttTo...............',
      '..................ottttTo...............',
      '..................ottttTo...............',
      '..................oTTTTTo...............',
      '..................oTTTTTo...............',
      '..................oTTTTTo...............',
      '..................ottttTo...............',
      '..................ottttTo...............',
      '..................ottttTo...............',
      '.................oTTTTTo................',
      '.................oTTTTTo................',
      '.................oTTTTTo................',
      '.................ottttTo................',
      '.................ottttTo................',
      '.................ottttTo................',
      '.................oTTTTTo................',
      '.................oTTTTTo................',
      '.................oTTTTTo................',
      '.................ottttTo................',
      '.................ottttTo................',
      '.................ottttTo................',
      '.................oTTTTTo................',
      '................oTTTTTTo................',
      '................oTTTTTTo................',
      '................otttttTo................',
      '................otttttTo................',
      '................otttttTo................',
      '................oTTTTTTo................',
      '................oTTTTTTo................',
      '................oTTTTTTo................',
      '................otttttTo................',
      '................otttttTo................',
      '................otttttTo................',
    ],
  },
  pine: {
    worldWidth: 1300,
    collide: 0.3,
    rows: [
      '..............oo..............',
      '.............oLLo.............',
      '.............oLLo.............',
      '............oLLLdo............',
      '............oLLLdo............',
      '............oLLldo............',
      '...........oLLLlddo...........',
      '...........oLLllddo...........',
      '...........oLLllddo...........',
      '..........oLLLLLdddo..........',
      '..........oLLLLLdddo..........',
      '..........oLdLLlddddo.........',
      '...........oLLLlddoo..........',
      '...........oLLllddo...........',
      '..........oLLLlldddo..........',
      '..........oLLllllddo..........',
      '.........oLLLlllldddo.........',
      '.........oLLllLLldddo.........',
      '........oLLLlLLLdddddo........',
      '........oLLlLLLldddddo........',
      '.......oLLLlLLllddddddo.......',
      '.......oLdlLLllllddddddo......',
      '........ooLLLlllldddooo.......',
      '.........oLLlllllddddo........',
      '........oLLllllllddddo........',
      '.......oLLLlllLLldddddo.......',
      '......oLLLlllLLldldddddo......',
      '......oLLlllLLLldddddddo......',
      '.....oLLlllLLLllddddddddo.....',
      '....oLLLlllLLllllddddddddo....',
      '....oLdlldLLllllldddddddddo...',
      '.....ooooLLllllllddddooooo....',
      '.......oLLLlllllldddddo.......',
      '......oLLLllllLLlldddddo......',
      '......oLLllllLLldlddddddo.....',
      '.....oLLllllLLllddddddddo.....',
      '....oLLllllLLllllddddddddo....',
      '...oLLLlllLLllllldddddddddo...',
      '..oLLLlllLLllllllddddddddddo..',
      '..odLldlLLllllllldddddddddddo.',
      '...ooooLLLlllllllldddddooooo..',
      '.....oLLLlllllllllddddddo.....',
      '....oLLLlllllllllldddddddo....',
      '...oLLLlllllllllllldddddddo...',
      '..oLLLlllllllllllllddddddddo..',
      '.oLLLlllllllllllllldddddddddo.',
      'oLLLlllllllllllllllddddddddddo',
      'oLLdlldlldlldlldlldldddddddddd',
      '.ooooooooooootttTooooooooooooo',
      '............otttTo............',
      '............otttTo............',
      '............otttTo............',
      '............otttTo............',
      '............otttTo............',
      '............otttTo............',
    ],
  },
  cactus: {
    worldWidth: 700,
    collide: 0.45,
    rows: [
      '..........oooo..........',
      '.........occcco.........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko..ooo...',
      '........oCckccko.occco..',
      '........oCckcckooCckcko.',
      '........oCckcckooCckcko.',
      '...ooo..oCckcckooCckcko.',
      '..occco.oCckcckooCckcko.',
      '.oCckckooCckcckooCckcko.',
      '.oCckckooCckcckooCckcko.',
      '.oCckckooCckcckooCckcko.',
      '.oCckckooCckcckooCckcko.',
      '.oCckckooCckcckooCckcko.',
      '.oCckckooCckcckooCckcko.',
      '.oCckckooCckcckooCckcko.',
      '.oCckckooCckcckooCckcko.',
      '.oCckckooCckcckooCckcko.',
      '.oCckckooCckccccccccco..',
      '.oCckckooCckccccccccco..',
      '.oCckckooCckccccccccco..',
      '.oCckckooCckcckkkkkkko..',
      '..occcccccckcckoooooo...',
      '..occcccccckccko........',
      '..occcccccckccko........',
      '..okkkkkkkckccko........',
      '...ooooooCckccko........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko........',
      '........oCckccko........',
    ],
  },
  bush: {
    worldWidth: 1000,
    collide: 0,
    rows: [
      '.............oooLooo............',
      '...........ooLLLLLLloo..........',
      '..........oLLLLLLLllllo.........',
      '.........oLLLLLLLllllllo........',
      '........ooLLLLLLllllllloooo.....',
      '.....oooLLLLLLLlllllllLLLLLoo...',
      '....oLLLLLLLLLllllllLLLLLLlllo..',
      '...oLLLLLLLLLllllllLLLLLLlllllo.',
      '..oLLLLLLLLLLllllllLLLLLllllllo.',
      '..oLLLLllLLLLLllllLLLLLllllllddo',
      '..oLLLllLLLLLllllLLLLLlllllldddo',
      '.oLLLlllLLLLlllllLLLLllllllddddo',
      '..oLllllLLLllllldLLLlllllddddddo',
      '..ollllLLLllllldLLLllllldddddddo',
      '..olllllLllllldddLllllldddddddo.',
      '...oddddddddddddddddddddddddddo.',
      '....oooooooooooooooooooooooooo..',
    ],
  },
  rock: {
    worldWidth: 900,
    collide: 0.8,
    rows: [
      '........oooooooooooo........',
      '......ooRRRRRRRRRRrroo......',
      '.....oRRRRRRRRRRRrrrrro.....',
      '....oRRRRRRRRRRrrrrrrrro....',
      '...oRRRRRRRRRRrrrrqrrrrro...',
      '..oRRRRRRRqRRrrrrrrqrrrrro..',
      '.oRRRRRRRRRqrrrrrrrrrrrrrqo.',
      '.oRRRRRRRRrrqrrrrrrrrrrrqqo.',
      'oRRRRRRRRrrrrrrrrrrrrrqqqqqo',
      'oRRRRRRrrrrrrrrrrrrrrqqqqqqo',
      'oRRRRRrrrrrrrrrrrrrrqqqqqqqo',
      'oRRRRrrrrrrrrrrrrrrqqqqqqqqo',
      'oRRRrrrrrrrrrrrrrqqqqqqqqqqo',
      '.orrrrrrrrrrrrrrqqqqqqqqqqo.',
    ],
  },
  signCurveLeft: {
    worldWidth: 700,
    collide: 0.15,
    rows: [
      '.oooooooooooooooooooooo.',
      'offffffffffffffffffffffo',
      'ofssssssssssssssssssssfo',
      'ofsssssssssmmmssssmmmsfo',
      'ofssssssssmmmssssmmmssfo',
      'ofsssssssmmmssssmmmsssfo',
      'ofssssssmmmssssmmmssssfo',
      'ofsssssmmmssssmmmsssssfo',
      'ofssssmmmssssmmmssssssfo',
      'ofssssmmmssssmmmssssssfo',
      'ofsssssmmmssssmmmsssssfo',
      'ofssssssmmmssssmmmssssfo',
      'ofsssssssmmmssssmmmsssfo',
      'ofssssssssmmmssssmmmssfo',
      'ofsssssssssmmmssssmmmsfo',
      'ofssssssssssssssssssssfo',
      'offffffffffffffffffffffo',
      '.oooooooooopPoooooooooo.',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
    ],
  },
  signCurveRight: {
    worldWidth: 700,
    collide: 0.15,
    rows: [
      '.oooooooooooooooooooooo.',
      'offffffffffffffffffffffo',
      'ofssssssssssssssssssssfo',
      'ofsmmmssssmmmsssssssssfo',
      'ofssmmmssssmmmssssssssfo',
      'ofsssmmmssssmmmsssssssfo',
      'ofssssmmmssssmmmssssssfo',
      'ofsssssmmmssssmmmsssssfo',
      'ofssssssmmmssssmmmssssfo',
      'ofssssssmmmssssmmmssssfo',
      'ofsssssmmmssssmmmsssssfo',
      'ofssssmmmssssmmmssssssfo',
      'ofsssmmmssssmmmsssssssfo',
      'ofssmmmssssmmmssssssssfo',
      'ofsmmmssssmmmsssssssssfo',
      'ofssssssssssssssssssssfo',
      'offffffffffffffffffffffo',
      '.oooooooooopPoooooooooo.',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
      '..........opPo..........',
    ],
  },
  billboard: {
    worldWidth: 2600,
    collide: 0.9,
    rows: [
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaawaaawawwwwwaawwwaawaaawaaaaaaaawwwaaaawwaaaaaaaaaaff',
      'ffaaaaaaaawbaawbwbbbbbwabbwawbaawbaaaaaawabbwaawabbaaaaaaaaaff',
      'ffaaaaaaaawwaawbwbaaaawbaawbwwaawbaaaaaawbaawbwabaaaaaaaaaaaff',
      'ffaaaaaaaawbwawbwwwwaawbaawbwbwawbaaaaaaawwwabwwwwaaaaaaaaaaff',
      'ffaaaaaaaawbawwbwbbbbawbaawbwbawwbaaaaaawabbwawbbbwaaaaaaaaaff',
      'ffaaaaaaaawbaawbwbaaaawbaawbwbaawbaaaaaawbaawbwbaawbaaaaaaaaff',
      'ffaaaaaaaawbaawbwwwwwaawwwabwbaawbaaaaaaawwwabawwwabaaaaaaaaff',
      'ffaaaaaaaaabaaababbbbbaabbbaabaaabaaaaaaaabbbaaabbbaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ooooooooooooppPoooooooooooooooooooooooooooooooooppPooooooooooo',
      '...........oppPo...............................oppPo..........',
      '...........oppPo...............................oppPo..........',
      '...........oppPo...............................oppPo..........',
      '...........oppPo...............................oppPo..........',
      '...........oppPo...............................oppPo..........',
      '...........oppPo...............................oppPo..........',
      '...........oppPo...............................oppPo..........',
      '...........oppPo...............................oppPo..........',
      '...........oppPo...............................oppPo..........',
      '...........oppPo...............................oppPo..........',
      '...........oppPo...............................oppPo..........',
      '...........oppPo...............................oppPo..........',
    ],
  },
  post: {
    worldWidth: 160,
    collide: 0.6,
    rows: [
      '..oooo.',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.oxxxxo',
      '.oxxxxo',
      '.oxxxxo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
      '.opppPo',
    ],
  },
  signFork: {
    worldWidth: 900,
    collide: 0.2,
    rows: [
      '.oooooooooooooooooooooooo.',
      'offffffffffffffffffffffffo',
      'ofssssssssssssssssssssssfo',
      'ofsssmmmssssssssssmmmsssfo',
      'ofsssmmmssssssssssmmmsssfo',
      'ofsssmmmmssssssssmmmmsssfo',
      'ofsssssmmmssssssmmmsssssfo',
      'ofssssssmmmssssmmmssssssfo',
      'ofsssssssmmmssmmmsssssssfo',
      'ofssssssssmmmmmmssssssssfo',
      'ofsssssssssmmmmsssssssssfo',
      'ofssssssssssmmssssssssssfo',
      'ofssssssssssmmssssssssssfo',
      'ofssssssssssmmssssssssssfo',
      'ofssssssssssmmssssssssssfo',
      'ofssssssssssmmssssssssssfo',
      'ofssssssssssssssssssssssfo',
      'ofssssssssssssssssssssssfo',
      'offffffffffffffffffffffffo',
      '.ooooooooooopPooooooooooo.',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
      '...........opPo...........',
    ],
  },
  checkpointGate: {
    worldWidth: 5600,
    collide: 0,
    rows: [
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwaawaaawawwwwwaawwwaawaaawawwwwaaawwwaaawwwaawaaawawwwwwaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaawaaawawaaawawaaaaawaaawawaawaawaaawawaaawaaawaaawaaawaaawaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaawaaaaawaaawawaaaaawaaaaawawaaawaaawawaaawaaawaaawwaawaaawaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaawaaaaawwwwwawwwwaawaaaaawwaaaawwwwaawaaawaaawaaawawawaaawaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaawaaaaawaaawawaaaaawaaaaawawaaawaaaaawaaawaaawaaawaawwaaawaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaawaaawawaaawawaaaaawaaawawaawaawaaaaawaaawaaawaaawaaawaaawaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwaawaaawawwwwwaawwwaawaaawawaaaaaawwwaaawwwaawaaawaaawaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff',
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ooooppppPoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooppppPooooo',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
    ],
  },
  goalGate: {
    worldWidth: 5600,
    collide: 0,
    rows: [
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ffabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbwwwbbbwwwbbbwwwbbwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbwbbbwbwbbbwbwbbbwbwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbwbbbbbwbbbwbwbbbwbwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbwbwwwbwbbbwbwwwwwbwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbwbbbwbwbbbwbwbbbwbwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbwbbbwbwbbbwbwbbbwbwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbwwwwbbwwwbbwbbbwbwwwwwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff',
      'ffbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbbabbff',
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      'ooooppppPoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooppppPooooo',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
      '...oppppPo...................................................................................................oppppPo....',
    ],
  },
};

